import { test, expect } from '@playwright/test';

test.describe('Create Invoice (Write Operation)', () => {
    test.beforeEach(async ({ page }) => {
        // Authenticate
        await page.goto('/auth/login');
        await page.fill('input[name="email"]', 'karthik5kashyapks@gmail.com');
        await page.fill('input[name="password"]', '12345678');
        await page.click('button[type="submit"]');
        await expect(page).toHaveURL(/.*dashboard/);
    });

    test('should successfully generate a new invoice', async ({ page }) => {
        // Navigate to new invoice form
        await page.goto('/billing/new');

        // Note: The form fetches patients, doctors, and procedures via API. 
        // We will click the select, wait for options to appear, and pick the first one.

        // 1. Select Patient (1st combobox)
        await page.getByRole('combobox').nth(0).click();
        await page.getByRole('option').first().waitFor({ state: 'visible' });
        await page.getByRole('option').first().click();

        // 2. Select Treating Doctor (2nd combobox)
        await page.getByRole('combobox').nth(1).click();
        await page.getByRole('option').first().waitFor({ state: 'visible' });
        await page.getByRole('option').first().click();

        // 3. Add a Line Item (manually fill description and unit price instead of relying on async procedure sync)
        await page.getByPlaceholder('Custom description...').first().fill('General Checkup (Auto-filled)');
        await page.locator('table input[type="number"]').nth(1).fill('500');

        // Check if GST is applied (the checkbox is active by default in the code)
        // Add Notes
        await page.getByPlaceholder('Add any special instructions or billing notes...').fill('Automated Test Invoice. Generated by Playwright.');

        // Save & Issue Invoice
        await page.getByRole('button', { name: /Save & Issue/i }).click();

        await page.waitForTimeout(1500);

        // Debug any potential error banners that appear
        const errorBanner = page.locator('.bg-red-50');
        if (await errorBanner.isVisible()) {
            const errorText = await errorBanner.innerText();
            throw new Error(`Validation Error on UI: ${errorText}`);
        }

        // Should automatically redirect back to the billing main ledger on success
        await expect(page).toHaveURL(/.*billing$/);

        // Verify we are back on the billing page showing the table
        await expect(page.locator('h2').filter({ hasText: 'Billing & Invoicing' })).toBeVisible();
    });
});
